Removed *`* because it crashes build
There was a mistake in [last commit](https://github.com/actions/starter-workflows/commit/5bb79fa367c673dd464152846ff75cf4461911dd),  that added additional *`* which causes this error 
```
/Users/runner/work/_temp/2259bec8-2d05-441b-ada0-fad594134af2.sh: line 5: unexpected EOF while looking for matching ``'
14
Error: Process completed with exit code 2.
```
I just simply removed it.